# Generated by Django 6.0.3 on 2026-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='famous_for',
            field=models.TextField(default=''),
        ),
    ]
