# Generated by Django 6.0.3 on 2026-06-23 06:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_savedplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
